<template>
  <div class="student-practice-page">
    <div class="practice-header"><div><h1>Python 练习</h1><p>独立练习空间，提交结果不会改变课程成绩。</p></div><el-tag type="success">已通过 {{ passedCount }}/{{ questions.length }}</el-tag></div>
    <div class="filter-row"><el-radio-group v-model="filter"><el-radio-button label="ALL">全部</el-radio-button><el-radio-button label="TODO">未完成</el-radio-button><el-radio-button label="DONE">已完成</el-radio-button><el-radio-button label="WRONG">错题</el-radio-button></el-radio-group></div>
    <div class="practice-layout"><el-card class="question-list" shadow="never"><template #header>我的题单</template><div v-for="section in sections" :key="section.key"><div class="section-label">{{ section.label }}</div><button v-for="item in section.items" :key="keyOf(item)" class="question-item" :class="{ active: activeKey === keyOf(item) }" @click="selectQuestion(item)"><span class="question-text">{{ item.sort_no }}. {{ item.question_content }}</span><small>{{ statusOf(item) }}</small></button></div><el-empty v-if="!sections.some(item => item.items.length)" description="暂无符合条件的练习" /></el-card>
      <el-card v-if="current" class="editor-card" shadow="never"><template #header><div class="editor-title"><span>{{ current.question_content }}</span><el-tag size="small">Python 3</el-tag></div></template><div class="statement">{{ current.question_content }}<div v-if="current.input_description" class="description"><b>输入说明：</b>{{ current.input_description }}</div><div v-if="current.output_description" class="description"><b>输出说明：</b>{{ current.output_description }}</div><div v-if="current.sample_explanation" class="description"><b>样例解释：</b>{{ current.sample_explanation }}</div><div v-if="current.publicCases?.length" class="sample-cases"><b>公开样例：</b><div v-for="item in current.publicCases" :key="item.snapshot_case_id" class="sample-case"><span>输入：{{ item.input_text || '（无）' }}</span><span>期望输出：{{ item.expected_output }}</span></div></div></div><div class="editor-shell"><div class="editor-head"><span>main.py</span><span>{{ draftState }}</span></div><div ref="editorElement" class="code-editor" /></div><div class="actions"><el-button :loading="saving" @click="saveDraft">保存草稿</el-button><el-button :loading="running" @click="run">运行示例</el-button><el-button type="primary" :loading="submitting" @click="submit">提交判题</el-button><el-button @click="previous">上一题</el-button><el-button @click="next">下一题</el-button></div><el-alert v-if="lastResult" class="result-alert" :title="resultTitle(lastResult)" :type="lastResult.status_code === 'ACCEPTED' ? 'success' : 'warning'" :closable="false" /><div v-if="history.length" class="history"><h3>最近提交</h3><el-table :data="history" size="small"><el-table-column prop="submitted_at" label="时间" width="170" /><el-table-column prop="submit_type" label="类型" width="90" /><el-table-column prop="status_message" label="状态" /><el-table-column prop="score" label="得分" width="80" /></el-table></div></el-card><el-empty v-else description="请从左侧选择一道题" /></div>
  </div>
</template>

<script setup>
import { autocompletion, completeFromList } from '@codemirror/autocomplete'
import { defaultKeymap, history as cmHistory, historyKeymap, indentWithTab } from '@codemirror/commands'
import { python } from '@codemirror/lang-python'
import { bracketMatching, defaultHighlightStyle, indentOnInput, syntaxHighlighting } from '@codemirror/language'
import { Compartment, EditorState } from '@codemirror/state'
import { EditorView, keymap, lineNumbers } from '@codemirror/view'
import { computed, nextTick, onMounted, onUnmounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getStudentPracticeOverview, getStudentPracticeQuestion, saveStudentPracticeDraft, submitStudentPractice } from '@/api/business/pythonPractice'
const questions = ref([]); const current = ref(null); const sourceCode = ref(''); const history = ref([]); const lastResult = ref(null); const activeKey = ref(''); const filter = ref('ALL'); const saving = ref(false); const running = ref(false); const submitting = ref(false); const draftState = ref('草稿未保存'); const editorElement = ref(null); let editorView; let pollTimer; let pollAttempts = 0
const passedCount = computed(() => questions.value.filter(item => item.progress?.passed_flag === '1').length)
const filteredQuestions = computed(() => questions.value.filter(item => { const progress = item.progress; if (filter.value === 'DONE') return progress?.passed_flag === '1'; if (filter.value === 'WRONG') return progress && progress.passed_flag !== '1' && progress.submit_count > 0; if (filter.value === 'TODO') return !progress || progress.passed_flag !== '1'; return true }))
const sections = computed(() => [{ key: 'BASE_VERSION', label: '基础题', items: filteredQuestions.value.filter(item => item.source_type === 'BASE_VERSION') }, { key: 'EXTENSION', label: '班级加练', items: filteredQuestions.value.filter(item => item.source_type === 'EXTENSION') }])
function keyOf(item) { return `${item.source_type}-${item.source_id}-${item.question_id}` }
function statusOf(item) { if (item.progress?.passed_flag === '1') return '已通过'; if (item.progress?.submit_count) return '待改进'; return '未开始' }
function resultTitle(item) { return `${item.status_message || '判题中'}${item.score == null ? '' : ` · ${item.score} 分`}（${item.passed_case_count || 0}/${item.total_case_count || 0}）` }
function mountEditor() { if (editorView || !editorElement.value) return; editorView = new EditorView({ state: EditorState.create({ doc: sourceCode.value, extensions: [lineNumbers(), python(), indentOnInput(), bracketMatching(), syntaxHighlighting(defaultHighlightStyle, { fallback: true }), cmHistory(), autocompletion({ override: [completeFromList(['print', 'input', 'if', 'else', 'for', 'while', 'range', 'len', 'int', 'str'].map(label => ({ label, type: 'keyword' })))] }), keymap.of([...defaultKeymap, ...historyKeymap, indentWithTab]), EditorView.updateListener.of(update => { if (update.docChanged) { sourceCode.value = update.state.doc.toString(); draftState.value = '草稿待保存' } }), EditorView.theme({ '&': { minHeight: '320px', fontSize: '14px' }, '.cm-content': { fontFamily: 'Consolas, "Courier New", monospace', padding: '14px 0' }, '.cm-scroller': { overflow: 'auto' } })] }), parent: editorElement.value }) }
function setCode(value) { sourceCode.value = value || ''; if (editorView && editorView.state.doc.toString() !== sourceCode.value) editorView.dispatch({ changes: { from: 0, to: editorView.state.doc.length, insert: sourceCode.value } }) }
async function selectQuestion(item) { clearTimeout(pollTimer); pollAttempts = 0; activeKey.value = keyOf(item); const res = await getStudentPracticeQuestion({ sourceType: item.source_type, sourceId: item.source_id, questionId: item.question_id }); current.value = res.data || {}; setCode(current.value.draft?.source_code || current.value.starter_code || ''); draftState.value = current.value.draft ? '草稿已保存' : '草稿未保存'; history.value = current.value.history || []; lastResult.value = history.value[0] || null; if (lastResult.value?.status_code === 'WAITING' || lastResult.value?.status_code === 'JUDGING') poll() }
async function saveDraft() { if (!current.value || saving.value) return; saving.value = true; try { await saveStudentPracticeDraft({ sourceType: current.value.source_type, sourceId: current.value.source_id, questionId: current.value.question_id, sourceCode: sourceCode.value }); draftState.value = '草稿已保存'; ElMessage.success('草稿已保存') } finally { saving.value = false } }
async function enqueue(type) { if (!current.value || !sourceCode.value.trim()) return ElMessage.warning('请先输入 Python 代码'); type === 'RUN' ? running.value = true : submitting.value = true; try { const res = await submitStudentPractice({ sourceType: current.value.source_type, sourceId: current.value.source_id, questionId: current.value.question_id, sourceCode: sourceCode.value, submitType: type }); lastResult.value = res.data || {}; poll() } finally { running.value = false; submitting.value = false } }
function run() { return enqueue('RUN') }; function submit() { return enqueue('SUBMIT') }
async function poll() { clearTimeout(pollTimer); if (pollAttempts >= 30) { lastResult.value = { ...(lastResult.value || {}), status_code: 'SERVICE_ERROR', status_message: '判题等待超时，请稍后刷新查看历史' }; return } pollAttempts += 1; pollTimer = setTimeout(async () => { if (!current.value) return; const res = await getStudentPracticeQuestion({ sourceType: current.value.source_type, sourceId: current.value.source_id, questionId: current.value.question_id }); const data = res.data || {}; history.value = data.history || []; lastResult.value = history.value[0] || lastResult.value; if (lastResult.value?.status_code === 'WAITING' || lastResult.value?.status_code === 'JUDGING') poll(); else { const overview = await getStudentPracticeOverview(); questions.value = overview.data?.questions || questions.value } }, 700) }
function currentIndex() { return filteredQuestions.value.findIndex(item => keyOf(item) === activeKey.value) }
function previous() { const index = currentIndex(); if (index > 0) selectQuestion(filteredQuestions.value[index - 1]) }
function next() { const index = currentIndex(); if (index >= 0 && index < filteredQuestions.value.length - 1) selectQuestion(filteredQuestions.value[index + 1]) }
onMounted(async () => { await nextTick(mountEditor); const res = await getStudentPracticeOverview(); questions.value = res.data?.questions || []; if (questions.value.length) await selectQuestion(questions.value[0]) })
onUnmounted(() => { clearTimeout(pollTimer); editorView?.destroy() })
</script>

<style scoped>.student-practice-page{padding:24px;max-width:1400px;margin:auto}.practice-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px}.practice-header h1{margin:0 0 6px;font-size:26px}.practice-header p{margin:0;color:#909399}.filter-row{margin-bottom:14px}.practice-layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:18px}.question-list{min-height:560px}.section-label{padding:8px 12px;background:#f5f7fa;color:#606266;font-weight:600}.question-item{display:flex;flex-direction:column;align-items:flex-start;width:100%;padding:12px;border:0;border-bottom:1px solid #ebeef5;background:#fff;text-align:left;cursor:pointer;color:#303133}.question-item:hover,.question-item.active{background:#ecf5ff;color:#409eff}.question-text{line-height:1.5;word-break:break-word}.question-item small{margin-top:6px;color:#909399}.editor-title,.actions{display:flex;align-items:center;justify-content:space-between;gap:10px}.statement{padding:12px;margin-bottom:14px;background:#f8fafc;line-height:1.7;white-space:pre-wrap}.description{margin-top:8px}.sample-cases{margin-top:10px}.sample-case{display:flex;flex-direction:column;gap:4px;margin-top:6px;padding:8px;background:#fff;border:1px solid #ebeef5;font-family:Consolas,"Courier New",monospace;white-space:pre-wrap;word-break:break-word}.editor-shell{overflow:hidden;border:1px solid #dcdfe6;border-radius:4px}.editor-shell:focus-within{border-color:#409eff;box-shadow:0 0 0 1px #409eff}.editor-head{display:flex;justify-content:space-between;padding:8px 12px;background:#f5f7fa;color:#606266;font:13px/1.4 Consolas,"Courier New",monospace}.code-editor{min-height:320px}.code-editor :deep(.cm-focused){outline:none}.actions{justify-content:flex-start;flex-wrap:wrap;margin-top:14px}.result-alert{margin-top:16px}.history{margin-top:24px}.history h3{font-size:16px}@media(max-width:800px){.student-practice-page{padding:12px}.practice-layout{grid-template-columns:1fr}.question-list{min-height:auto}.practice-header{gap:12px}.filter-row{overflow:auto;white-space:nowrap}}</style>
