<template>
  <div class="app-container python-practice-page">
    <div class="page-heading"><div><h2>Python 刷题</h2><p>年级基础题统一开放，班级加练只追加题目，不计入课程成绩。</p></div><el-button v-if="canManagePython" type="primary" @click="openCreate">新建题单</el-button></div>
    <el-card shadow="never"><el-table v-loading="loading" :data="plans" row-key="plan_id"><el-table-column prop="plan_name" label="题单名称" min-width="180" /><el-table-column prop="grade" label="年级" width="80" /><el-table-column prop="entry_year" label="适用届别" width="110" /><el-table-column label="发布状态" width="110"><template #default="{ row }"><el-tag :type="row.version_status === 'PUBLISHED' ? 'success' : 'info'">{{ row.version_status === 'PUBLISHED' ? '已发布' : '草稿' }}</el-tag></template></el-table-column><el-table-column label="操作" width="340"><template #default="{ row }"><el-button v-if="canManagePython" link type="primary" @click="openPlan(row)">修改题单</el-button><el-button v-if="canViewAnalytics" link type="primary" @click="openAnalytics(row)">查看班级情况</el-button><el-button v-if="canManagePython" link type="danger" @click="removePlan(row)">删除题单</el-button><span v-if="!canManagePython">仅可查看已发布题单</span></template></el-table-column></el-table><el-empty v-if="!loading && !plans.length" description="暂无 Python 题单" /></el-card>

    <el-dialog v-model="dialogVisible" title="新建 Python 基础题单" width="460px"><el-form :model="form" label-width="90px"><el-form-item label="题单名称"><el-input v-model="form.planName" /></el-form-item><el-form-item label="年级"><el-input-number v-model="form.grade" :min="1" :max="12" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建</el-button></template></el-dialog>

    <el-drawer v-model="drawerVisible" title="配置基础题与班级加练" size="72%"><template v-if="currentPlan"><div class="plan-summary"><b>{{ currentPlan.plan_name }}</b><span>基础题对全年级生效</span></div><el-alert v-if="currentPlan.version_status === 'PUBLISHED'" title="本题单正在投放，新增或移除题目会立即更新学生练习入口；已有提交记录会保留。修改题目后点击“发布更新”即可立即生效。" type="info" :closable="false" /><div class="section-title"><span>基础题</span><div><el-button size="small" @click="openQuestionPicker">从题库选择</el-button><el-button type="success" size="small" @click="publish">{{ currentPlan.version_status === 'PUBLISHED' ? '发布更新' : '发布给全年级' }}</el-button></div></div><el-table :data="currentPlan.questions || []" size="small"><el-table-column prop="sort_no" label="序号" width="70" /><el-table-column prop="question_id" label="题目 ID" width="100" /><el-table-column prop="question_content" label="题面" show-overflow-tooltip /><el-table-column prop="stage" label="阶段" width="110" /><el-table-column label="操作" width="80"><template #default="{ row }"><el-button link type="danger" @click="removeQuestion(row)">移除</el-button></template></el-table-column></el-table><div class="section-title"><span>班级加练</span><el-button size="small" @click="openExtension">新建加练包</el-button></div><el-table :data="extensions" size="small"><el-table-column prop="extension_name" label="名称" /><el-table-column prop="question_count" label="题数" width="70" /><el-table-column prop="status" label="状态" width="90" /><el-table-column label="操作" width="220"><template #default="{ row }"><el-button link size="small" @click="addExtensionQuestion(row)">加入题目</el-button><el-button v-if="row.status === 'DRAFT'" link type="success" size="small" @click="publishExtension(row)">发布</el-button><el-button v-else-if="row.status === 'PUBLISHED'" link type="warning" size="small" @click="retractExtension(row)">撤回</el-button></template></el-table-column></el-table></template></el-drawer>

    <el-dialog v-model="extensionDialog" title="新建班级加练包" width="500px"><el-form :model="extensionForm" label-width="90px"><el-form-item label="加练名称"><el-input v-model="extensionForm.extensionName" /></el-form-item><el-form-item label="目标班级"><el-select v-model="extensionForm.classes" multiple clearable placeholder="请选择班级" style="width:100%"><el-option v-for="cls in managedClasses" :key="classKey(cls)" :label="classLabel(cls)" :value="classCode(cls)" /></el-select></el-form-item></el-form><template #footer><el-button @click="extensionDialog = false">取消</el-button><el-button type="primary" @click="createExtension">保存草稿</el-button></template></el-dialog>

    <el-dialog v-model="questionPickerVisible" title="选择 Python 题目" width="1000px" append-to-body><el-form :inline="true" @submit.prevent><el-form-item label="难度"><el-select v-model="questionQuery.difficulty" clearable placeholder="全部难度" style="width:140px" @change="loadQuestionOptions"><el-option label="简单" value="SIMPLE" /><el-option label="中等" value="MEDIUM" /><el-option label="困难" value="HARD" /></el-select></el-form-item><el-form-item label="题面"><el-input v-model="questionQuery.questionContent" clearable placeholder="搜索题目内容" @keyup.enter="loadQuestionOptions" /></el-form-item><el-button type="primary" @click="loadQuestionOptions">搜索</el-button></el-form><el-table v-loading="questionLoading" :data="questionOptions" size="small" max-height="420"><el-table-column prop="questionId" label="题目ID" width="90" /><el-table-column prop="questionContent" label="题面" min-width="460" show-overflow-tooltip /><el-table-column label="难度" width="90"><template #default="{ row }">{{ difficultyLabel(row.difficulty) }}</template></el-table-column><el-table-column label="操作" width="180"><template #default="{ row }"><el-button link type="primary" @click="previewQuestion(row)">查看题目</el-button><el-button link type="primary" :disabled="selectedQuestionIds.has(row.questionId)" @click="addQuestion(row)">{{ selectedQuestionIds.has(row.questionId) ? '已加入' : '加入题单' }}</el-button></template></el-table-column></el-table><pagination v-show="questionTotal > 0" :total="questionTotal" v-model:page="questionQuery.pageNum" v-model:limit="questionQuery.pageSize" @pagination="loadQuestionOptions" /></el-dialog>
    <el-dialog v-model="previewVisible" title="Python 题目预览" width="760px" append-to-body><template v-if="previewQuestionData"><h3 class="preview-title">{{ previewQuestionData.questionContent }}</h3><div class="preview-meta">题目 ID：{{ previewQuestionData.questionId }}　年级：{{ previewQuestionData.grade }}</div><el-descriptions :column="1" border><el-descriptions-item label="输入说明">{{ previewConfig.inputDescription || '无' }}</el-descriptions-item><el-descriptions-item label="输出说明">{{ previewConfig.outputDescription || '无' }}</el-descriptions-item><el-descriptions-item label="样例">{{ previewCases.map(item => `输入：${item.inputText || '无'}；输出：${item.expectedOutput}`).join('；') || '暂无样例' }}</el-descriptions-item><el-descriptions-item label="限制条件">{{ previewConfig.constraintsText || '无' }}</el-descriptions-item><el-descriptions-item label="起始代码"><pre class="preview-code">{{ previewConfig.starterCode || '暂无' }}</pre></el-descriptions-item></el-descriptions></template></el-dialog>

    <el-dialog v-model="classPickerVisible" title="选择班级查看学习情况" width="620px" append-to-body><el-alert title="请选择一个你负责的班级，系统将展示该班级的题目进度和提交情况。" type="info" :closable="false" /><el-radio-group v-model="selectedClassCode" class="class-picker"><el-radio-button v-for="cls in analyticsClasses" :key="classKey(cls)" :label="classCode(cls)">{{ classLabel(cls) }}</el-radio-button></el-radio-group><template #footer><el-button @click="classPickerVisible = false">取消</el-button><el-button type="primary" :disabled="!selectedClassCode" @click="confirmAnalyticsClass">查看情况</el-button></template></el-dialog>
    <el-drawer v-model="analyticsDrawer" title="班级学习情况" size="60%"><el-alert v-if="analyticsPlan" :title="`${analyticsPlan.plan_name}：班级学习情况`" type="info" :closable="false" /><el-table :data="analyticsRows" size="small" class="analytics-table"><el-table-column prop="student_name" label="学生" width="120" /><el-table-column prop="class_code" label="班级" width="80" /><el-table-column prop="question_id" label="题目 ID" width="100" /><el-table-column prop="best_score" label="最高分" width="90" /><el-table-column prop="passed_flag" label="是否通过" width="90"><template #default="{ row }">{{ row.passed_flag === '1' ? '已通过' : '未通过' }}</template></el-table-column><el-table-column prop="submit_count" label="提交次数" width="90" /><el-table-column prop="last_practice_time" label="最近练习" /></el-table><el-empty v-if="!analyticsRows.length" description="暂无练习记录" /></el-drawer>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { listQuestion } from '@/api/business/question'
import { getMyClasses } from '@/api/business/teacherClass'
import { addTeacherExtensionQuestion, addTeacherQuestion, createTeacherExtension, createTeacherPlan, deleteTeacherPlan, getTeacherAnalytics, getTeacherExtensions, getTeacherPlan, getTeacherPlans, publishTeacherExtension, publishTeacherPlan, removeTeacherQuestion, retractTeacherExtension } from '@/api/business/pythonPractice'
import { getProgrammingQuestion } from '@/api/business/programming'
import useUserStore from '@/store/modules/user'

const userStore = useUserStore()
const canManagePython = computed(() => userStore.roles.includes('admin') || userStore.roles.includes('teacher'))
const canViewAnalytics = computed(() => canManagePython.value)

const plans = ref([]), loading = ref(false), saving = ref(false), dialogVisible = ref(false), drawerVisible = ref(false), extensionDialog = ref(false), analyticsDrawer = ref(false), questionPickerVisible = ref(false), classPickerVisible = ref(false)
const currentPlan = ref(null), extensions = ref([]), analyticsRows = ref([]), analyticsPlan = ref(null), managedClasses = ref([]), analyticsClasses = ref([]), selectedClassCode = ref(''), pendingAnalyticsPlan = ref(null), pendingExtensionRow = ref(null)
const questionOptions = ref([]), questionTotal = ref(0), questionLoading = ref(false)
const previewVisible = ref(false), previewQuestionData = ref(null), previewConfig = ref({}), previewCases = ref([])
const form = reactive({ planName: '', grade: 7 }), extensionForm = reactive({ extensionName: '', classes: [] }), questionQuery = reactive({ pageNum: 1, pageSize: 10, questionType: 'practical', practicalMode: 'PYTHON', difficulty: '', questionContent: '' })
const selectedQuestionIds = computed(() => new Set((currentPlan.value?.questions || []).map(item => Number(item.question_id))) )
async function load() { loading.value = true; try { plans.value = (await getTeacherPlans()).data || [] } finally { loading.value = false } }
function openCreate() { Object.assign(form, { planName: '', grade: 7 }); dialogVisible.value = true }
function difficultyLabel(value) { return value === 'SIMPLE' ? '简单' : value === 'HARD' ? '困难' : '中等' }
async function create() { if (!form.planName.trim()) return ElMessage.warning('请填写题单名称'); saving.value = true; try { await createTeacherPlan(form); ElMessage.success('题单已创建'); dialogVisible.value = false; await load() } finally { saving.value = false } }
async function removePlan(row) { try { const published = row.version_status === 'PUBLISHED'; await ElMessageBox.confirm(published ? `确定删除题单“${row.plan_name}”吗？学生将不再看到该题单，已有练习记录会保留。` : `确定删除草稿题单“${row.plan_name}”吗？题单中的配置也会一并删除。`, '删除题单', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }); await deleteTeacherPlan(row.plan_id); ElMessage.success(published ? '题单已停止投放' : '题单已删除'); await load() } catch (error) { if (error !== 'cancel') throw error } }
async function openPlan(row) { currentPlan.value = (await getTeacherPlan(row.plan_id)).data || {}; extensions.value = (await getTeacherExtensions(row.plan_id)).data || []; drawerVisible.value = true }
function openQuestionPicker() { pendingExtensionRow.value = null; questionPickerVisible.value = true; loadQuestionOptions() }
async function loadQuestionOptions() { questionLoading.value = true; try { const res = await listQuestion({ ...questionQuery }); questionOptions.value = res.rows || res.data?.rows || []; questionTotal.value = res.total || res.data?.total || questionOptions.value.length } finally { questionLoading.value = false } }
async function previewQuestion(row) { const res = await getProgrammingQuestion(Number(row.questionId)); previewQuestionData.value = row; previewConfig.value = res.data || {}; previewCases.value = res.testCases || []; previewVisible.value = true }
async function addQuestion(row) { if (pendingExtensionRow.value) { await addTeacherExtensionQuestion(pendingExtensionRow.value.extension_id, { questionId: Number(row.questionId), sortNo: Number(pendingExtensionRow.value.question_count || 0) + 1 }); extensions.value = (await getTeacherExtensions(currentPlan.value.plan_id)).data || []; ElMessage.success('题目已加入加练包') } else { await addTeacherQuestion(currentPlan.value.plan_version_id, { questionId: Number(row.questionId), sortNo: (currentPlan.value.questions || []).length + 1 }); currentPlan.value = (await getTeacherPlan(currentPlan.value.plan_id)).data || {}; ElMessage.success('题目已加入题单') } }
async function removeQuestion(row) { try { await ElMessageBox.confirm(`确定从题单移除“${row.question_content}”吗？已有学生提交记录会保留。`, '移除题目', { type: 'warning', confirmButtonText: '移除', cancelButtonText: '取消' }); await removeTeacherQuestion(currentPlan.value.plan_version_id, row.question_id); currentPlan.value = (await getTeacherPlan(currentPlan.value.plan_id)).data || {}; ElMessage.success('题目已移除') } catch (error) { if (error !== 'cancel') throw error } }
async function publish() { await publishTeacherPlan(currentPlan.value.plan_id, currentPlan.value.plan_version_id); ElMessage.success('题单已发布'); await openPlan(currentPlan.value); await load() }
function openExtension() { Object.assign(extensionForm, { extensionName: '', classes: [] }); extensionDialog.value = true }
async function createExtension() { if (!extensionForm.extensionName.trim() || !extensionForm.classes.length) return ElMessage.warning('请填写名称并选择班级'); await createTeacherExtension(currentPlan.value.plan_id, { extensionName: extensionForm.extensionName, entryYear: currentPlan.value.entry_year, classes: extensionForm.classes }); extensionDialog.value = false; extensions.value = (await getTeacherExtensions(currentPlan.value.plan_id)).data || []; ElMessage.success('加练包草稿已保存') }
async function addExtensionQuestion(row) { pendingExtensionRow.value = row; questionPickerVisible.value = true; await loadQuestionOptions() }
async function publishExtension(row) { await publishTeacherExtension(row.extension_id); ElMessage.success('加练包已发布'); extensions.value = (await getTeacherExtensions(currentPlan.value.plan_id)).data || [] }
async function retractExtension(row) { await retractTeacherExtension(row.extension_id); ElMessage.success('加练包已撤回'); extensions.value = (await getTeacherExtensions(currentPlan.value.plan_id)).data || [] }
async function openAnalytics(row) { if (!canViewAnalytics.value) { ElMessage.info('当前角色没有班级学情权限'); return } pendingAnalyticsPlan.value = row; analyticsClasses.value = managedClasses.value.filter(cls => String(cls.entryYear || cls.entry_year) === String(row.entry_year)); selectedClassCode.value = ''; classPickerVisible.value = true }
async function confirmAnalyticsClass() { const row = pendingAnalyticsPlan.value; classPickerVisible.value = false; analyticsPlan.value = row; analyticsRows.value = (await getTeacherAnalytics({ sourceType: 'BASE_VERSION', sourceId: row.plan_version_id, entryYear: row.entry_year, classCode: selectedClassCode.value })).data || []; analyticsDrawer.value = true }
function classCode(cls) { return String(cls.classCode || cls.class_code || '').replace(/[^\d]/g, '') }
function classLabel(cls) { return `${classCode(cls)}班${cls.entryYear || cls.entry_year ? `（${cls.entryYear || cls.entry_year}届）` : ''}` }
function classKey(cls) { return `${classCode(cls)}-${cls.entryYear || cls.entry_year || ''}` }
onMounted(async () => { await load(); if (canViewAnalytics.value) { try { const res = await getMyClasses(); managedClasses.value = res.data || [] } catch (error) { ElMessage.warning('班级列表加载失败，暂时无法查看班级学情') } } })
</script>

<style scoped>.page-heading{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px}.page-heading h2{margin:0 0 6px}.page-heading p{margin:0;color:#909399}.plan-summary,.section-title{display:flex;justify-content:space-between;align-items:center;gap:12px}.plan-summary{margin:14px 0;color:#606266}.section-title{margin:22px 0 10px;font-weight:600}.analytics-table{margin-top:16px}.class-picker{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}.preview-title{margin:0 0 8px}.preview-meta{color:#909399;margin-bottom:16px}.preview-code{white-space:pre-wrap;background:#f6f8fa;padding:10px;margin:0}.python-practice-page :deep(.el-card){border-radius:6px}@media(max-width:700px){.page-heading,.section-title{align-items:flex-start;flex-direction:column}.section-title>div{display:flex;flex-wrap:wrap;gap:6px}}</style>
